namespace TeamSuneat
{
    public enum GamePrefTypes
    {
        // Log
        LOG_LEVEL_PROCESS,
        LOG_LEVEL_INFO,
        LOG_LEVEL_WARNING,
        LOG_LEVEL_ERROR,
        LOG_LEVEL_EXCEPT,

        // Option-Language
        OPTION_LANGUAGE,

        // Option-Audio
        OPTION_MASTER_VOLUME,
        OPTION_MUSIC_VOLUME,
        OPTION_AMBIENCE_VOLUME,
        OPTION_SFX_VOLUME,
        OPTION_MUTE_MUSIC,
        OPTION_MUTE_SFX,

        // Option-Video
        OPTION_USE_FULLSCREEN,
        OPTION_USE_BORDERLESS,
        OPTION_USE_VSYNC,
        OPTION_USE_PARTICLE_EFFECT,
        OPTION_USE_FRAME_RATE_CAP,
        OPTION_RESOLUTION_X,
        OPTION_RESOLUTION_Y,
        OPTION_RESOLUTION_REFRESH_RATE,

        // Option-Play
        OPTION_CAMERA_SHAKE,
        OPTION_VIBRATION,
        OPTION_SHOW_MONSTER_LIFE_TEXT,

        OPTION_SHOW_ITEM_OPTION_RANGE,
        OPTION_SHOW_ITEM_OPTION_COMPARE,

        OPTION_USE_TUTORIAL,
        OPTION_USE_MONSTER_GAUGE,
        OPTION_USE_DAMAGE_TEXT,
        OPTION_USE_STATE_EFFECT_TEXT,
        OPTION_USE_GAMEPLAY_TIMER,

        // Option-Play (Developer)
        OPTION_SHOW_MONSTER_ATTACK_COOLDOWN,
        OPTION_SHOW_INVULNERABLE_RENDERER,
        OPTION_SHOW_ALL_BUFF_ICONS,
        OPTION_SHOW_STATUS_CALCULATIONS,
        OPTION_IS_HIDE_USERINTERFACE,
        OPTION_IS_HIDE_NPC_MARKER,

        // Option-Control

        KEYBOARD_MOVEUP,
        KEYBOARD_MOVEDOWN,
        KEYBOARD_MOVELEFT,
        KEYBOARD_MOVERIGHT,
        KEYBOARD_JUMP,
        KEYBOARD_ATTACK,
        KEYBOARD_SUBATTACK,
        KEYBOARD_CAST1,
        KEYBOARD_CAST2,
        KEYBOARD_CAST3,
        KEYBOARD_CAST4,
        KEYBOARD_POTION1,
        KEYBOARD_INTERACT,
        KEYBOARD_ORDERINTERACT,
        KEYBOARD_POPUPSKILL,
        KEYBOARD_POPUPINVENTORY,
        KEYBOARD_POPUPITEM,
        KEYBOARD_COMPARE,
        KEYBOARD_SYNERGY,
        KEYBOARD_KEYBINDING,
        KEYBOARD_WORLDDIFFICULTY,

        // Cheat
        GAME_CHEAT_INFINITY_DAMAGE,
        GAME_CHEAT_PERCENT_DAMAGE,
        GAME_CHEAT_ONE_DAMAGE_ATTACK,

        GAME_CHEAT_CRITICAL_TYPE,
        GAME_CHEAT_PASSIVE_TRIGGER_CHANCE_TYPE,

        GAME_CHEAT_NOT_COST_RESOURCE,
        GAME_CHEAT_NO_COOLDOWN_TIME,
        GAME_CHEAT_RECEIVE_DAMAGE_ONLY_ONE,
        GAME_CHEAT_NOT_DEAD,
        GAME_CHEAT_NOT_CROWD_CONTROL,
        GAME_CHEAT_DONT_DROP_ITEM,
        GAME_CHEAT_FULL_POTIONS,
        GAME_CHEAT_ITEM_OPTION_MAX_STAT,
        GAME_CHEAT_CUSTOM_RELIC_GRADE,
        GAME_CHEAT_MONSTER_SKILL_INDEX,

        // Stage
        VISIBLE_CAMERA_COLLISION_CULLING_MASK,

        // Early Access
        EARLY_ACCESS_ENTER_NOTICE,

        // Blacksmith
        BLACKSMITH_ITEM_ENHANCE,
        BLACKSMITH_ITEM_TRANSCEND,
    }
}